[package]
name = "sieve-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
#mail-parser = { git = "https://github.com/stalwartlabs/mail-parser" } 
mail-parser = { path = "/home/vagrant/code/mail-parser" } 
phf = { version = "0.11", features = ["macros"] }
serde = { version = "1.0", features = ["derive"] }
ahash = { version = "0.8.0" }

[dev-dependencies]
serde_json = "1.0"
