[package]
name = "sieve-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
phf = { version = "0.11", features = ["macros"] }
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3.3"

[dev-dependencies]
serde_json = "1.0"
